services:
  db:
   image: postgres:latest
   restart: always
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=todo
   ports:
    - "5433:5432"
   networks:
    - custom
networks:
  custom:
   driver: bridge
